apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ridehail
resources:
  - ridehail.yaml
configMapGenerator:
  - name: keycloak-realm
    files:
      - ridehail-realm.json
generatorOptions:
  disableNameSuffixHash: true
