server:
  port: 8081
spring:
  application:
    name: trip-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      properties: {enable.idempotence: true}
    consumer:
      auto-offset-reset: earliest
  datasource:
    url: jdbc:postgresql://localhost:5432/ridehail
    username: ridehail
    password: ridehail
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    table: trip_flyway_history
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
