spring:
  datasource:
    hikari:
      data-source-properties:
        sslmode: ${POSTGRES_SSL_MODE:verify-full}
  kafka:
    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL:SSL}
      sasl.mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
      sasl.jaas.config: ${KAFKA_SASL_JAAS_CONFIG:}
  data:
    redis:
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:true}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
